Traceback (most recent call last):
  File "/home/dako/Documents/meta_crag_submissions/llama3_new/sft_unsloth.py", line 105, in <module>
    ).cast_column("image", Image())  # keep PIL objects
                           ^^^^^^^
TypeError: 'module' object is not callable
Traceback (most recent call last):
  File "/home/dako/Documents/meta_crag_submissions/llama3_new/sft_unsloth.py", line 105, in <module>
    ).cast_column("image", Image())  # keep PIL objects
                           ^^^^^^^
TypeError: 'module' object is not callable
